# Generated by Django 5.0.2 on 2025-07-20 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('currency_code', models.CharField(max_length=3, unique=True, verbose_name='Currency code')),
                ('currency_name', models.CharField(max_length=50, verbose_name='Currency name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Currency symbol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is default')),
                ('decimal_places', models.PositiveIntegerField(default=2, verbose_name='Decimal places')),
                ('thousands_separator', models.CharField(default=',', max_length=1, verbose_name='Thousands separator')),
                ('decimal_separator', models.CharField(default='.', max_length=1, verbose_name='Decimal separator')),
            ],
            options={
                'verbose_name': 'Currency Configuration',
                'verbose_name_plural': 'Currency Configurations',
                'ordering': ['currency_code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('from_currency', models.CharField(max_length=3, verbose_name='From currency')),
                ('to_currency', models.CharField(max_length=3, verbose_name='To currency')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Exchange rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['from_currency', 'to_currency'],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='UserCurrencyPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Preferred currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_preference', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Currency Preference',
                'verbose_name_plural': 'User Currency Preferences',
            },
        ),
    ]
